onboarding = false

[terminal]
default_shell = "fish"

[keys]
prefix = "ctrl+h"
settings = "prefix+shift+s"
reload_config = "prefix+r"
new_workspace = "prefix+shift+c"
rename_tab = "prefix+comma"
split_horizontal = "prefix+s"
resize_mode = "prefix+shift+r"

[ui]
prompt_new_tab_name = false
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = false

[experimental]
pane_history = true

[theme]
name = "rose-pine"
auto_switch = true
