import = ["~/Developer/Source/alacritty-theme/themes/kanagawa_wave.toml"]

[cursor]
style = "Block"

[debug]
persistent_logging = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MonoLisa Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MonoLisa Nerd Font Mono"
style = "SemiBold Regular"

[font.italic]
family = "MonoLisa Nerd Font Mono"
style = "Italic"

[scrolling]
history = 1000
multiplier = 5

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i", "-l", "-c", "tmux attach || tmux new-session -A -s main"]

[window]
dynamic_title = false
option_as_alt = "OnlyLeft"
title = "First, solve the problem. Then, write the code."

[window.dimensions]
columns = 128
lines = 32

[window.padding]
x = 5
y = 5

