import = ["~/.config/alacritty/themes/ristretto.toml"]

[cursor]
style = "Block"

[debug]
persistent_logging = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.offset]
x = 0
y = 5

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font Mono"
style = "Medium"

[font.italic]
family = "GeistMono Nerd Font Mono"
style = "Italic"

[scrolling]
history = 1000
multiplier = 5

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i", "-l"]

[window]
dynamic_title = false
option_as_alt = "OnlyLeft"
title = "Make it work, make it right, make it fast."
decorations = "Buttonless"

[window.dimensions]
columns = 128
lines = 32

[window.padding]
x = 5
y = 5

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
