theme = "cendre"

[editor]
line-number = "relative"
color-modes = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
auto-signature-help = false

[keys.insert]
C-y = "completion"
