[settings]
experimental = true

[tools]
lua-language-server = "latest"
node = "lts"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:oxlint" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:oxfmt" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:typescript-language-server" = "latest"
"npm:svelte-language-server" = "latest"
"npm:hunkdiff" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
clojure = "latest"
babashka = "latest"
odin = "latest"
zig = "latest"
zls = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
