#!/bin/env sh

# QT must be able to find my theme
# export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# X Settings
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# Disable PC-Speaker
xset b off &

# Disable power-saving
xset -dpms

# Disable screen-saver
xset s off

# Key repeat
xset r rate 300 80

# Set the left cursor as default
xsetroot -cursor_name left_ptr

# Hide the mouse cursor
unclutter -idle 3 &

# Dvorak keyboard
setxkbmap dvorak 

# Restore the keyboard setup if it's plugged in again
# inputplug -c ~/.bin/on_new_keyboard.sh

# I want to be able to sleep at night
redshift -l 52:4 -t 6000:4800 -m randr &

# Keychain for managing SSH agent
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# sxhkd, used for key bindings does not work well with Fish
export SXHKD_SHELL=/usr/bin/bash

# I only want to type my SSH password once
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Extra paths for dmenu
export PATH="$HOME/.local/bin:$HOME/.npm/bin:$HOME/.cargo/bin:$HOME/lib/elixir/bin:$PATH:$HOME/projects/go/bin"

# Default terminal for i3
export TERMINAL=/bin/alacritty

# Start the eww daemon
eww daemon

#
# Start BSPWM and log its output for debugging
#
exec bspwm >/tmp/bspwm-$(date +'%F-%k-%M-%S').log 2>&1

