#!/bin/env sh

# QT must be able to find my theme
# export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# X Settings
xrdb -merge .Xresources

# Disable PC-Speaker
xset b off &

# Disable power-saving
xset -dpms

# Disable screen-saver
xset s off

# Key repeat
xset r rate 300 80

# Set the left cursor as default
xsetroot -cursor_name left_ptr

# Hide the mouse cursor
unclutter -idle 3 &

# Dvorak keyboard
setxkbmap dvorak 

# Restore the keyboard setup if it's plugged in again
inputplug -c ~/.bin/on_new_keyboard.sh

# I want to be able to sleep at night
redshift -l 52:4 -t 6000:4800 -m randr &

# Keychain for managing SSH agent
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Extra paths for dmenu
export PATH="$HOME/bin:$HOME/.npm/bin:$HOME/.cargo/bin:$HOME/lib/elixir/bin:$PATH:$HOME/projects/go/bin"

# Default terminal for i3
export TERMINAL=/bin/alacritty

#
# Start window manager
#
exec i3
