#!/bin/env sh

# QT must be able to find my theme
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# X Settings
xrdb -merge .Xresources
xrdb -merge .Xdefaults

# Disable PC-Speaker
xset b off &

# Disable power-saving
xset -dpms

# Disable screen-saver
xset s off

# Key repeat
xset r rate 300 60

# Set the left cursor as default
xsetroot -cursor_name left_ptr

# Start rvxt-unicode server
urxvtd -o -q -f &

# Hide the mouse cursor
unclutter -idle 3 &

# Clipboard functionality
parcellite -n -d &

# Be nice for my eyes at night
redshift -l 52:4 -t 6000:4800 -m randr &

# Set background
feh --bg-tile ~/pictures/wallpapers/grey_wash_wall.png

# Thunar
thunar --daemon &

# SSH agent
eval `ssh-agent`

# Emacs
emacs --daemon &

# Authentication agent
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# VMWare
/usr/bin/vmware-user &

#
# Start window manager
#
exec xmonad > $HOME/.xmonad.log 2>&1
