#!/bin/env sh

# QT must be able to find my theme
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Set the correct DPI
xrandr --dpi 192

# X Settings
xrdb .Xresources

# Disable PC-Speaker
xset b off &

# Disable power-saving
xset -dpms

# Disable screen-saver
xset s off

# Key repeat
xset r rate 300 80

# Extra keybindings
xbindkeys &

# Enable DPMS (power saving of manitor)
xset +dpms

# Set the left cursor as default
xsetroot -cursor_name left_ptr

# Hide the mouse cursor
unclutter -idle 3 &

# Lock it down! But only do it manually.
# Currently hangs when screen is turned off...
# light-locker --no-lock-on-suspend &

# Dvorak keyboard
setxkbmap dvorak -option ctrl:nocaps

# Set background
feh --bg-tile ~/pictures/wallpapers/patterns/naturalblack.png

# Bluetooth management
blueman-applet &

# I want to be able to sleep at night
redshift -l 52:4 -t 6000:4800 -m vidmode &

# Easy mounting of USB disks
udiskie --no-automount --no-notify --tray --use-udisks2 &

# Keychain for managing SSH agent
eval $(export SHELL=sh; keychain --agents ssh --nogui --eval --quiet)

# Add my own path to bin, needed for dmenu
export PATH="$HOME/bin:$HOME/.npm/bin:$HOME/.cargo/bin:$HOME/lib/elixir/bin:$PATH:$HOME/projects/go/bin"

# Set the GOPATH
export GOPATH="$HOME/projects/go"

# Add Rust source path for Emacs
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
