#!/usr/bin/env bash
SERVICE="syncthing"
USER="workera"
PORT=2104
OPTS="--no-browser \
	--home=/home/$USER/.config/syncthing \
	--gui-address=http://127.0.0.1:$PORT \
	--logfile=/home/$USER/.config/syncthing/syncthing.log"

if ! pgrep -x "$SERVICE" >/dev/null
then
        daemonize /usr/bin/syncthing serve $OPTS
fi
