# ROSE PINE DAWN THEME BEGIN

# Rose Pine Dawn palette
color_fg="#575279"
color_com="#797593"
color_ui="#9893A5"
color_sel="#DFDAD9"
color_float="#FFFAF3"
color_bg="#FAF4ED"

color_red="#B4637A"
color_orange="#D7827E"
color_yellow="#EA9D34"
color_green="#286983"
color_cyan="#56949F"
color_blue="#286983"
color_magenta="#907AA9"

# by default window names will just be their index
set-option -g automatic-rename              on
set-option -g automatic-rename-format       "#I"

# set to 12 for a 12-hour clock
set-option -g clock-mode-style              24
set-option -g clock-mode-colour             "$color_green"

# NOTE: color variable expansion only works in double quotes
set-option -g status-fg                     "$color_fg"
set-option -g status-bg                     "$color_float"
set-option -g copy-mode-current-match-style "fg=$color_bg,bg=$color_yellow"
set-option -g copy-mode-match-style         "fg=$color_bg,bg=$color_blue"
set-option -g menu-selected-style           "fg=$color_bg,bg=$color_blue"
set-option -g menu-style                    "fg=$color_fg,bg=$color_float"
set-option -g message-style                 "bg=$color_yellow,fg=$color_bg"
set-option -g message-command-style         "bg=$color_sel,fg=$color_fg"
set-option -g mode-style                    "bg=$color_sel,fg=$color_fg"
set-option -g pane-active-border-style      "fg=$color_blue"
set-option -g pane-border-lines             "heavy"
set-option -g pane-border-style             "fg=$color_sel"
set-option -g popup-border-lines            "rounded"
set-option -g status-right-style            "fg=$color_com"
set-option -g window-status-current-style   "fg=$color_blue"
set-option -g window-status-style           "fg=$color_com"
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# display the window index number or index-number:name if has a name
set-option -g window-status-separator      ''
set-option -g window-status-format         '#[fg=#797593]#[bg=#FFFAF3] #{?#{==:#W, },#I,#I #[fg=#9893A5]#[bg=#DFDAD9] #W }'
set-option -g window-status-current-format '#[fg=#575279]#[bg=#FAF4ED]#[bold] #{?#{==:#W, },#I,#I #[fg=#286983]#[bg=#DFDAD9] #W }'

# status right will show the current session name if there is more than one session
set-option -g status-right                 '#{?#{>:#{server_sessions},1}, #[fg=#286983]◆ #[fg=#575279]#{session_name} ,}'
set-option -g status-left                  ''
# ROSE PINE DAWN THEME END
