typeset -U path
path=(~/bin ~/go/bin $path)

# Go
# ==
if type go >/dev/null 2>&1; then
    typeset -xTU GOPATH gopath
    gopath=$HOME/go
    path=(~/go/bin $path)

    # installed by homebrew
    if type brew >/dev/null 2>&1; then
        path=($(brew --prefix)/opt/go/libexec/bin $path)
    fi
fi
