# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="kphoen"
export CASE_SENSITIVE="true"

plugins=(git)
if [ `uname` = "Darwin" ]; then
   plugins+=(brew osx)
fi

if [ `uname` = "Linux" ]; then
   plugins+=(archlinux)
fi

source $ZSH/oh-my-zsh.sh

# Aliasen and environment
source ~/.zshalias
source ~/.zshenv

# Check for a .venv file. If it's there, activate it.
has_virtualenv() {
  if [ -e .venv ] && [ -z "$VIRTUAL_ENV" ]; then
    workon "$@" `cat .venv`
  fi
}
venv_cd () {
  cd "$@" && has_virtualenv
}
alias cd="venv_cd"

# Bindings for Emacs
bindkey -e

# Don't use autocorrect
unsetopt correct_all

# Evaluate keychan
if [ `uname` = "Darwin" ]; then
   eval `keychain --eval --agents ssh --inherit any id_rsa`
else
   eval `keychain --eval --agents ssh id_rsa`
fi

# CTRL-R for backwards history search
bindkey "^r" history-incremental-search-backward