autoload -U colors && colors            # setup colors
autoload -U promptinit && promptinit    # setup prompt
autoload -U compinit && compinit        # enable autcompletion
zmodload -i zsh/complist

# options
setopt   HIST_IGNORE_DUPS               # ignore duplicates in history
unsetopt CORRECT_ALL                    # don't correct anything
bindkey -e                              # emacs keybindings
prompt pure                             # simple prompt

# completions
_zshcompdir=/usr/local/share/zsh-completions
[[ -z $fpath[(r)$_zshcompdir]  ]] && fpath=($fpath $_zshcompdir)

_sitecompdir=/usr/local/share/zsh/site-functions
[[ -z $fpath[(r)$_sitecompdir]  ]] && fpath=($fpath $_sitecompdir)

# autojump on mac
[[ -s /usr/local/etc/profile.d/autojump.sh ]] && . /usr/local/etc/profile.d/autojump.sh

# autojump on freebsd
[[ -s /usr/local/share/autojump/autojump.zsh ]] && . /usr/local/share/autojump/autojump.zsh

# aliases
source ~/.zshalias

export PATH="$HOME/.cargo/bin:$PATH"
