# -*- mode: shell-script -*-
# ~/.bash_aliases
#

if [ `uname` == "Linux" ]; then
    alias ls="ls --color=auto"
fi
alias et="emacsclient -a \"\" -t"
alias e="emacsclient -a \"\" -nq"
alias v="vim"
alias rust-update="curl -s https://static.rust-lang.org/rustup.sh | sudo sh"

if hash hub 2>/dev/null; then
    eval "$(hub alias -s)"
fi
