# -*- mode: shell-script -*-
# ~/.bash_aliases
#

if [ ! `uname` == "FreeBSD" ]; then
    alias ls="ls --color=auto"
fi
alias e="emacs"
alias v="vim"

if hash gh 2>/dev/null; then
    eval "$(gh alias -s)"
fi
