# -*- mode: shell-script -*-
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/wunki/Source/google-cloud-sdk/path.bash.inc ]; then
    source /Users/wunki/Source/google-cloud-sdk/path.bash.inc
fi

# The next line enables bash completion for gcloud.
if [ -f /Users/wunki/Source/google-cloud-sdk/completion.bash.inc ]; then
    source /Users/wunki/Source/google-cloud-sdk/completion.bash.inc
fi

export NVM_DIR="/home/wunki/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
