# -*- mode: shell-script -*-
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# The next line updates PATH for the Google Cloud SDK.
source /Users/wunki/Source/google-cloud-sdk/path.bash.inc

# The next line enables bash completion for gcloud.
source /Users/wunki/Source/google-cloud-sdk/completion.bash.inc
